/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Submitted trade details
 */
export class TradeSubmitted extends SpeakeasyBase {
  /**
   * Unique ID for this trade that you defined.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "client_trade_id" })
  clientTradeId?: string;

  /**
   * Unique ID for this trade provided by Clear Street.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "trade_id" })
  tradeId?: string;
}
