/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Represents an upload's details
 */
export class Upload extends SpeakeasyBase {
    /**
     * Timestamp when the upload was created; milliseconds since unix epoch
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: number;

    /**
     * Name of the upload; this will be the filename if the upload
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The orgID of the user who created this upload
     */
    @SpeakeasyMetadata()
    @Expose({ name: "org_id" })
    orgId: number;

    /**
     * AWS S3 key
     */
    @SpeakeasyMetadata()
    @Expose({ name: "s3_key" })
    s3Key: string;

    /**
     * SHA256 hash of the trades you uploaded. This uniquely identifies your upload
     */
    @SpeakeasyMetadata()
    @Expose({ name: "upload_id" })
    uploadId: string;

    /**
     * The userID of the user who created this upload
     */
    @SpeakeasyMetadata()
    @Expose({ name: "user_id" })
    userId: number;
}
